### ISSUE TITLE
Recommended branch

### ISSUE THREAD

**Issue by sizun** [cta-observatory/nectarchain#1]
Hi @jlenain,

The README.md says to use the nectarCAM_reader branch of @FrancaCassol 's fork?
Is it still the recommended practice?
Last I checked, the master branches of cta-observatory/ctapipe_io_nectarcam and cta-observatory/ctapipe worked OK?

**Comment by jlenain** [comment]
Hi @sizun ,

Good catch.
In my earlier attempts, I had to use @FrancaCassol 's fork to be able to read NectarCAM data.
I'll check now with the upstream master, and update the instructions if necessary.

**Comment by jlenain** [comment]
Hi @sizun ,

At this moment, I was unable to make the master branches of cta-observatory/ctapipe_io_nectarcam and cta-observatory/ctapipe work together. As small modification of `ctapipe_io_nectarcam` can fix it, I opened a pull request at [cta-observatory/ctapipe_io_nectarcam#2](https://github.com/cta-observatory/ctapipe_io_nectarcam/pull/2)

**Comment by jlenain** [comment]
Solved through #5
