### ISSUE TITLE
SPE fit algorithm: account for fit convergence to set valid status

### ISSUE THREAD

**Issue by tibaldo** [cta-observatory/nectarchain#106]
While looking at he new implementation of the gain calibration via SPE fitting using run 3936, I found that for two pixels I got poor results with the fitted function not matching the data
![fit_SPE_pixel658](https://github.com/cta-observatory/nectarchain/assets/3046743/4799f335-912e-4591-8c0e-3ee9f03fc309)
![fit_SPE_pixel660](https://github.com/cta-observatory/nectarchain/assets/3046743/5a2d13f0-ec68-415c-9110-4a861a341c54)
Yet, the gain value is not flagged in the results file, that is, it has 'is_valid = True'.
By looking at the code it seems that presently the only condition to set 'is_valid = True' is that the fit algorithm returns some values. I think the fit convergence should be also taken into account to avoid this kind of problem.
I explored this is my branch [tibaldo:spefit_convergence_issues](https://github.com/tibaldo/nectarchain/tree/spefit_convergence_issues) and it seems rather straighforward. In this exemple of a possible implementation I checked three outputs from Minuit: fit convergence status, validity of parameters and that the parameters have not reached their limits.
What do you think @guillaumegrolleron @jlenain? If that seems like a good addition I can make any modifications needed and then make a pull request from my branch.
PS: I did not dig into the origin of the problem for the two pixels. For pixel 658 there is a failure in the preliminary Gaussian fits to set the starting value for the parameters, for pixel 660 the charge distribution looks unusual, but I'm unsure if it is just a plot range feature.

**Comment by jlenain** [comment]
Hi @tibaldo , sorry for the delay and thanks for this!
Indeed, it would be very useful to add some criteria to flag fit results as valid. The ones you implemented in https://github.com/tibaldo/nectarchain/tree/spefit_convergence_issues seem fully valid, so yes, please go ahead with a pull request, that would be much appreciated!

**Comment by tibaldo** [comment]
@guillaumegrolleron let me know how you want to proceeds, whatever works for me
