### ISSUE TITLE
pytables 3.7 needed

### ISSUE THREAD

**Issue by frnbrun** [cta-observatory/nectarchain#28]
An issue can occur while reading a data file : ctapipe_io_nectarcam reads an hdf5 file to apply some calibration coefficients. This can fail due to filters issue if the version of pytables is < 3.7. 

Description of the issue can be found here : https://github.com/PyTables/PyTables/issues/811. The changes mentioned are included in PyTables v3.7, this should be added to the environment.yml file as a requirement.

**Comment by tibaldo** [comment]
This should also be fixed in ctapipe_io_nectarcam

**Comment by jlenain** [comment]
> This should also be fixed in ctapipe_io_nectarcam

Thanks @tibaldo ! Now part of https://github.com/cta-observatory/ctapipe_io_nectarcam/pull/32 throught the commit https://github.com/cta-observatory/ctapipe_io_nectarcam/pull/32/commits/65d69a634dd457884d8b22ce96d226f821906c2b
