### ISSUE TITLE
NectarCam geometry

### ISSUE THREAD

**Issue by sizun** [cta-observatory/nectarchain#4]
Hello @FrancaCassol

I am confused by the CameraDisplay obtained with the current geometry file [NectarCam-002.camgeom.fits.gz](https://github.com/cta-observatory/ctapipe-extra/blob/master/ctapipe_resources/NectarCam-002.camgeom.fits.gz), using either the CameraFrame or the EngineeringCameraFrame coordinate system:

![ctapipe_camera_display](https://user-images.githubusercontent.com/6674040/62140578-87fbde00-b2eb-11e9-9307-da06682e0b9f.png)

The displays do not correspond to the view I am used too e.g. looking at the camera from the dish, x points right, y points up (which according to the doc of these classes is the MAGIC/FACT convention the engineering frame should provide?). In this frame, for NectarCam, the pixel numbers should increase like this:

![nectarcam_pixel_numbers_xyCAM](https://user-images.githubusercontent.com/6674040/62141211-79fa8d00-b2ec-11e9-8a49-11c0b388e143.png)

**Comment by FrancaCassol** [comment]
Hi @sizun,

sorry I am not sure to understand the question ( these geometries are always rather confusing for me too). Is it not that you should look at the pixel index from behind the camera not from the front?

**Comment by kosack** [comment]
I think the NectarCam-002 file seems to have the X and Y axes swapped, at least with respect to the simulation version. I think in the EngineeringCameraFrame, it should look like the bottom figure in Patrick's digram (but right now it is rotated or flipped 90 deg).  That will cause problems in the reconstruction later also.

**Comment by kosack** [comment]
In the simulations (prod3) it looks ok, except that the pixel numbering is obviously not correct

**Comment by FrancaCassol** [comment]
I would say that I see a swap left to right of the x axis (the pixel zero is on the right instead of the left)...

**Comment by FrancaCassol** [comment]
Just to be sure, the EngineeringCameraFrame should be like the figure of Patrick?

**Comment by sizun** [comment]
> In the simulations (prod3) it looks ok, except that the pixel numbering is obviously not correct

The pixel numbering was discussed with the MC group (see [issue #22534](https://forge.in2p3.fr/issues/22534)) but I am not sure from which prod it is supposed to be taken into account.

**Comment by FrancaCassol** [comment]
If I swap both axis I get this geometry (where I highlight the first 3 pixels). There is still a  top-bottom problem?

![geometry_003](https://user-images.githubusercontent.com/32127708/62192137-56c7f000-b375-11e9-8edc-e9a215d2212d.png)

**Comment by sizun** [comment]
> If I swap both axis I get this geometry (where I highlight the first 3 pixels).
With EngineeringCameraFrame?
>There is still a top-bottom problem?
Yes, if I understand the coordinate system correctly.

**Comment by FrancaCassol** [comment]
This what I have with the two frames.
@kosack what do you think about that?

![geometry_003](https://user-images.githubusercontent.com/32127708/62200524-e7a6c780-b385-11e9-89bd-55014bb8b20a.png)

**Comment by sizun** [comment]
I made a geometry 004 that leads to the displays I expect (by editing pix_x, pix_y and PIX_ROT):

![ctapipe_camgeom_004](https://user-images.githubusercontent.com/6674040/62279187-e17a1f00-b449-11e9-9967-0f2b1b5a6e84.png)

What do you think? I highlighted pixels 0,1,2,441,927.

**Comment by FrancaCassol** [comment]
Hi,
it seems good to me, but I leave @kosack to judge, in the case it is ok, please call it 003 and PR in ctapipe-extra with the same naming convention of the 002. I will then modify the nectarcam io package, in order to take this version as default.
