### ISSUE TITLE
Move to latest ctapipe for dependency (ctapipe-0.19)

### ISSUE THREAD

**Issue by dkerszberg** [cta-observatory/nectarchain#46]

**Comment by dkerszberg** [comment]
to be done at the same time for https://github.com/cta-observatory/ctapipe_io_nectarcam

**Comment by jlenain** [comment]
This should goes in hand with such an update on the [ctapipe_io_nectarcam](https://github.com/cta-observatory/ctapipe_io_nectarcam) side.

I would also propose to first tackle #36 , this will ease spotting any deep API change to be taken care of.

**Comment by vmarandon** [comment]
As my mac is too recent to install in a straight forward way nectarchain, I've started to work on transitioning to ctapipe 0.18.
For [ctapipe_io_nectarcam](https://github.com/cta-observatory/ctapipe_io_nectarcam), so far the changes needed are relatively small (cf my branch : [ctapipe018](https://github.com/vmarandon/ctapipe_io_nectarcam/tree/ctapipe018)) but I'm still testing things.

I haven't started yet for nectarchain.
