### ISSUE TITLE
"b" of equation 4 of Caroff et al. 2019

### ISSUE THREAD

**Issue by sona-patel** [cta-observatory/nectarchain#77]
Hello all,

Can someone tell, if I am looking at the correct version of Caroff et al. 2019? 

Eq. 4 is as shown in screenshot:
![Screenshot from 2023-09-14 11-24-57](https://github.com/cta-observatory/nectarchain/assets/16776228/e3a679a5-ab32-4f03-b101-4246fe613645)

If its the correct version then [here](https://github.com/cta-observatory/nectarchain/blob/347bf80b08f4ea954a9e0747c26b88cb233261d5/src/nectarchain/calibration/NectarGain/SPEfit/utils.py#L108), isn't there should be **2 to 3rd power inside np.sqrt(2 / np.pi)** ? and **factor of 2 (before p)** should not be there ?

Thank you :-)

**Comment by jlenain** [comment]
Hi @sona-patel ,

I don't think there is any typo here:
```latex
\sqrt{2/\pi} * 2 = 2*\sqrt{2} / \sqrt{\pi} = 2^{3/2} / \sqrt{\pi}
```
It is just that:
```python
np.sqrt(2/np.pi)*2
```
is numerically more economical than:
```python
np.sqrt(np.power(2,3/2)/np.pi)
```

**Comment by sona-patel** [comment]
Ahh, my bad - thanks!
