### ISSUE TITLE
Problem with DQM after refactoring

### ISSUE THREAD

**Issue by mdpunch** [cta-observatory/nectarchain#83]
**Describe the bug**

In the version after refactoring (`__version__== '0.1.6.dev13+gc4a163d'`) the command `start_dqm.py` doesn't work.

**To Reproduce**
1. activate the nectarchain dev env
2. try e.g. `python ../nectarchain/src//nectarchain/dqm/start_dqm.py -r 4332 $NECTARCAMDATA $NECTARCAMDATA`
3. get error: ``` File "/scr/punch/CTA/NectarCAM_muons/../nectarchain/src//nectarchain/dqm/start_dqm.py", line 53, in <module>
    from nectarchain.data.container import utils
ImportError: cannot import name 'utils' from 'nectarchain.data.container' (/scr/punch/CTA/nectarchain/src/nectarchain/data/container/__init__.py)```
4. Then, start `ipython`
5. 
```
from nectarchain.data.container import utils
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[9], line 1
----> 1 from nectarchain.data.container import utils

ImportError: cannot import name 'utils' from 'nectarchain.data.container' (/scr/punch/CTA/nectarchain/src/nectarchain/data/container/__init__.py)
```
7. ... panic ...

**Expected behavior**
Expect container to be imported correctly

**Supporting information**

**Additional context**
@jlenain guesses that this is due to the major refactoring effort.

**Comment by jlenain** [comment]
Hi @mdpunch ,
Thanks for reporting this!
This is not related to the DQM directly, but on the automatic mechanism to download data from DIRAC, which was in `nectarchain.data.container.utils` and has been moved into `nectarchain.data.management` following the code refactoring from #78 and #82 . We'll fix this asap.

**Comment by mdpunch** [comment]
Okay, that worked for that bug, thanks... now on to the next one!
